# Generated by Django 4.0.1 on 2024-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firststepApp', '0004_alter_participation_apprenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='presences',
        ),
    ]
