# Generated by Django 4.0.1 on 2024-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firststepApp', '0005_remove_participation_presences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='apprenant',
            field=models.IntegerField(),
        ),
    ]
